# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Jacob/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Jacob/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Jacob/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
C = np.zeros(10)
print(C)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [5]:
Z = np.zeros((10, 10))
print(Z.itemsize)
print("%d bytes" % (Z.size * Z.itemsize))

8
800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
# %run `python -c "import numpy; numpy.info(numpy.add)"`
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
# noticed that the 'arrange' doen't show the last number. Why?
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [8]:
Z = np.arange(50)
print(Z)
Z_reverse = Z[::-1]
print(Z_reverse)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [10]:
A = np.array([1, 2, 0, 0, 4, 0])
print(A[np.nonzero(A)])

[1 2 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
A = np.eye(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
A = np.random.random([3, 3, 3])
# A=np.random.random(27).reshape(3,3,3)
print(A)

[[[0.64203657 0.76112536 0.28204327]
  [0.7075897  0.27853127 0.97633595]
  [0.92795807 0.50451868 0.4243975 ]]

 [[0.50125269 0.54801123 0.14279178]
  [0.02219572 0.2746293  0.26833946]
  [0.72109883 0.7969512  0.75958275]]

 [[0.97901423 0.14207102 0.35779485]
  [0.48277566 0.62414427 0.81490159]
  [0.45109014 0.94339834 0.42844065]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
A = np.random.random([10, 10])
min_A, max_A = A.min(), A.max()
# min_A=np.min(A)
# max_A=np.max(A)
print(min_A, max_A)

0.003499697150647907 0.9762021922682669


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
A = np.random.random(30)
print(A.mean())

0.4989082637368412


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
A = np.ones((10, 10))
A[1:-1, 1:-1] = 0
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
# What is function pad?
A = np.ones((10, 10))
A = np.pad(A, pad_width=1, mode='constant', constant_values=0)
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)  # not a number is always not a number
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))  # nan can be an element in a set
print(0.3 == 3 * 0.1)  # how to fix it?

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
Z = np.diag(1+np.arange(4), k=-1)  # what is diag? what does k mean?
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
Z = np.zeros((8, 8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
# This is another solution
Z = np.ones((8, 8), dtype=int)
Z[1::2, ::2] = 0
Z[::2, 1::2] = 0
print(Z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
A = np.arange(6*7*8).reshape(6, 7, 8)
print(A[1, 5, 4])
print(np.unravel_index(100, (6, 7, 8)))

100
(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
Z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
Z = np.random.random((5, 5))
Z = (Z-np.mean(Z))/(np.std(Z))
print(Z)

[[ 1.41607366 -0.85512661  0.57148941  1.66364867 -0.70742347]
 [ 1.21823506 -0.45989459 -1.31065447 -1.07627257 -1.09389992]
 [ 1.4331838   0.90078998 -1.06857171  0.56676847 -1.01392447]
 [ 0.35577844  0.55327376  0.59004073 -1.19140943 -0.58899794]
 [ 1.53476384  0.82974517 -0.90855581 -0.99857947 -0.36048052]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [2]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [3]:
A = np.random.random([5, 3])
B = np.random.random([3, 2])
np.dot(A, B)

array([[0.75932439, 0.41056073],
       [0.3721084 , 0.19717865],
       [1.09999164, 0.5316021 ],
       [0.84401915, 0.48921783],
       [1.03928974, 0.4964447 ]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [24]:
Z = np.arange(11)
Z[(3 <= Z) & (Z <= 8)] *= -1  # what is '*=' ?
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [39]:
from numpy import *
print(sum(range(5), -1))
# from numpy import * will use numpy.sum() instead sum()
print(sum(range(5), -1))
# numpy.sum(a,b) mean sum(a) from dimension b, b=-1 means the last dimension
# see the case below
print(sum([[1, 2, 3], [4, 5, 6]], 0))
print(sum([[1, 2, 3], [4, 5, 6]], 1))
print(sum([[1, 2, 3], [4, 5, 6]], -1))

10
10
[5 7 9]
[ 6 15]
[ 6 15]


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [26]:
# Z**Z
print(2 << Z >> 2)
print(Z < -Z)
# 1j*Z
print(Z/1/1)
# Z<Z>Z

[        0         1         2 268435456 134217728  67108864  33554432
  16777216   8388608       256       512]
[False False False  True  True  True  True  True  True False False]
[ 0.  1.  2. -3. -4. -5. -6. -7. -8.  9. 10.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [40]:
np.array(0)/np.array(0)
np.array(0)//np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\Jacob\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Jacob\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
Z = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 8.  2.  3. 10.  8. -2. -2.  6. -1.  8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print(np.intersect1d(Z1, Z2))

[1 2 3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
# defaults = np.seterr(all="ignore")
Z = np.ones(1)/0
print(Z)

[inf]


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [41]:
np.sqrt(-1) == np.emath.sqrt(-1)
print(np.emath.sqrt(-1))

1j


C:\Users\Jacob\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [42]:
yesterday = np.datetime64('today', 'D')-np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D')+np.timedelta64(1, 'D')

print(yesterday)
print(today)
print(tomorrow)

2019-03-15
2019-03-16
2019-03-17


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [43]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [48]:
A = np.random.uniform(0, 10, 10)
print(A)
print(A-A % 1)  # % do not need int
print(np.floor(A))
print(np.ceil(A)-1)
print(A.astype(int))  # this will be int result
print(np.trunc(A))

[8.82372232 5.95156724 7.72697775 3.12195062 0.24492967 0.70841358
 4.7412334  2.92876146 1.58533356 7.49154628]
[8. 5. 7. 3. 0. 0. 4. 2. 1. 7.]
[8. 5. 7. 3. 0. 0. 4. 2. 1. 7.]
[8. 5. 7. 3. 0. 0. 4. 2. 1. 7.]
[8 5 7 3 0 0 4 2 1 7]
[8. 5. 7. 3. 0. 0. 4. 2. 1. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [54]:
Z = np.zeros((5, 5))
Z += np.arange(5)
A = np.zeros((5, 5))+np.arange(5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [1]:
def generate():
    for x in range(10):
        yield x
        
A = np.fromiter(generate(), dtype=float, count=-1)
# what's the differents with A=np.arange(0,10)
print(A)
np.info(np.fromiter)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
fromiter(iterable, dtype, count=-1)

Create a new 1-dimensional array from an iterable object.

Parameters
----------
iterable : iterable object
    An iterable object providing data for the array.
dtype : data-type
    The data-type of the returned array.
count : int, optional
    The number of items to read from *iterable*.  The default is -1,
    which means all data is read.

Returns
-------
out : ndarray
    The output array.

Notes
-----
Specify `count` to improve performance.  It allows ``fromiter`` to
pre-allocate the output array, instead of resizing it on demand.

Examples
--------
>>> iterable = (x*x for x in range(5))
>>> np.fromiter(iterable, float)
array([  0.,   1.,   4.,   9.,  16.])


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [69]:
# Z=np.linspace(0,1,11,endpoint=False)[1:]
Z = np.linspace(0, 1, 12, endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [6]:
Z = np.random.random(10)
print(id(Z))
Z.sort()
# using .sort will have the same id. using Z=np.sort(Z) will have different id.
print(id(Z))
print(Z)
np.info(np.sort)

2078188980304
2078188980304
[0.08268264 0.24526693 0.3327722  0.50724972 0.62141943 0.64890691
 0.68505487 0.73531172 0.85536008 0.91906425]
 sort(a, axis=-1, kind='quicksort', order=None)

Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. Default is 'quicksort'.
order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second, etc.  A single field can
    be specified as a string, and not all fields need be specified,
    but unspecified fields will still be used, in the order in which
    they come up in the dtype, to break ties.

Returns
-------
sorted_array : ndarray
    Array of the same type and shape as 

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [7]:
A = range(10)
print(np.add.reduce(A))  # what is reduce?
np.info(np.add.reduce)

45
reduce(a, axis=0, dtype=None, out=None, keepdims=False, initial)

Reduces `a`'s dimension by one, by applying ufunc along one axis.

Let :math:`a.shape = (N_0, ..., N_i, ..., N_{M-1})`.  Then
:math:`ufunc.reduce(a, axis=i)[k_0, ..,k_{i-1}, k_{i+1}, .., k_{M-1}]` =
the result of iterating `j` over :math:`range(N_i)`, cumulatively applying
ufunc to each :math:`a[k_0, ..,k_{i-1}, j, k_{i+1}, .., k_{M-1}]`.
For a one-dimensional array, reduce produces results equivalent to:
::

 r = op.identity # op = ufunc
 for i in range(len(A)):
   r = op(r, A[i])
 return r

For example, add.reduce() is equivalent to sum().

Parameters
----------
a : array_like
    The array to act on.
axis : None or int or tuple of ints, optional
    Axis or axes along which a reduction is performed.
    The default (`axis` = 0) is perform a reduction over the first
    dimension of the input array. `axis` may be negative, in
    which case it counts from the last to the first axis.

    .. versionadded:: 1.7.0

   

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [74]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A, B)
print(equal)
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A, B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [10]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1
# you also cannot change Z by '''Z += 1''' 

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [76]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y, X)  # arctan2?
print(R)
print(T)

[0.86738159 0.94224655 1.14759111 0.42146352 0.64391135 0.42941131
 1.35454682 0.57938572 0.98506649 0.5728434 ]
[1.06475926 1.12430142 0.96316073 0.12411868 0.31309948 0.06262083
 0.74104616 0.78163008 1.22042192 0.21030145]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [81]:
Z = np.random.random(10)
# Z[Z.argmin()]=0
Z[Z.argmax()] = 0
print(Z)

[0.80466971 0.52801519 0.36781254 0.36144355 0.88181541 0.75212121
 0.61886342 0.         0.29766503 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [36]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.arange(0,1.25,0.25),
                             np.arange(0,1.25,0.25))
# linspcace is smiliar to arange?
# Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
#                              np.linspace(0,1,5))

print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [41]:
X = np.arange(5)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)
print(np.linalg.det(C))

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4       ]
 [ 0.4         0.66666667  2.         -2.         -0.66666667]
 [ 0.28571429  0.4         0.66666667  2.         -2.        ]]
-131.91659501325745


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [44]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [19]:
np.set_printoptions(threshold=np.inf)  # np.inf vs. np.nan
Z=np.zeros((16, 16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [1]:
Z = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

80


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [13]:
Z = np.zeros(10, [('position', [('x', float, 1),
                                ('y', float, 1)]),
                  ('color',    [('r', float, 1),
                                ('g', float, 1),
                                ('b', float, 1)])])
print(Z[1]['position']['x'])
print(Z)

0.0
[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [28]:
# Z = np.random.random((100, 2))
# X, Y = np.atleast_2d(Z[:, 0], Z[:, 1])
# D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
# print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((100,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.66858597 0.17973366 0.62175737 0.66011987 0.41969115
  0.90104609 0.60681266 0.91649584 0.4508519 ]
 [0.66858597 0.         0.53850172 0.58524259 0.2221116  0.26303479
  0.44802883 0.26334462 0.267549   0.31735256]
 [0.17973366 0.53850172 0.         0.65267016 0.58284774 0.32559038
  0.72435595 0.54357114 0.76736794 0.27954974]
 [0.62175737 0.58524259 0.65267016 0.         0.38256354 0.43705076
  1.02448643 0.32460854 0.82273489 0.68844898]
 [0.66011987 0.2221116  0.58284774 0.38256354 0.         0.25740444
  0.6697543  0.06890595 0.44024672 0.45531513]
 [0.41969115 0.26303479 0.32559038 0.43705076 0.25740444 0.
  0.62470488 0.22380031 0.52802246 0.25256624]
 [0.90104609 0.44802883 0.72435595 1.02448643 0.6697543  0.62470488
  0.         0.70933974 0.33466331 0.45271885]
 [0.60681266 0.26334462 0.54357114 0.32460854 0.06890595 0.22380031
  0.70933974 0.         0.50035431 0.44894716]
 [0.91649584 0.267549   0.76736794 0.82273489 0.44024672 0.52802246
  0.33466331 0.50035

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [31]:
Z = np.arange(10, dtype=np.float32)
print(id(Z))
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [32]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [33]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [34]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2 / (2.0 * sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [36]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [47]:
X = np.random.rand(5, 10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-0.45565695 -0.1328889   0.26878296  0.4414986  -0.14487855  0.21519232
  -0.44245796 -0.14460814  0.19988967  0.19512695]
 [-0.11409088  0.197165   -0.3378333  -0.20055153  0.13031714  0.20470696
   0.43118501  0.30690883 -0.32874769 -0.28905954]
 [ 0.31840056  0.13783069 -0.1036668  -0.07422089  0.46554817 -0.19923218
  -0.38175803 -0.25998065  0.18092366 -0.08384453]
 [-0.65463892 -0.04311948  0.15900647 -0.01920663  0.09334525  0.28645214
  -0.12238214  0.14444031  0.29441581 -0.13831281]
 [ 0.50302928 -0.44201995 -0.27778676  0.08437095  0.22190984 -0.00217204
   0.2693708  -0.36864471  0.08111062 -0.06916801]]


#### 59. How to sort an array by the nth column? (★★☆)

In [33]:
A = np.random.random((5, 5))
print(A)
print(A[A[:, 0].argsort(), :])

[[0.25330733 0.02257259 0.87532762 0.78663896 0.20922753]
 [0.36279584 0.41128155 0.75490818 0.90700881 0.13997014]
 [0.9590805  0.88730548 0.2144857  0.37997301 0.27415559]
 [0.49984341 0.62564049 0.09685369 0.47870879 0.8653593 ]
 [0.59739284 0.92659041 0.52997816 0.71684694 0.73241712]]
[[0.25330733 0.02257259 0.87532762 0.78663896 0.20922753]
 [0.36279584 0.41128155 0.75490818 0.90700881 0.13997014]
 [0.49984341 0.62564049 0.09685369 0.47870879 0.8653593 ]
 [0.59739284 0.92659041 0.52997816 0.71684694 0.73241712]
 [0.9590805  0.88730548 0.2144857  0.37997301 0.27415559]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [45]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0).any()))

[[0 1 0 0 1 2 2 2 0 2]
 [0 0 2 0 1 0 2 2 0 1]
 [0 2 0 0 1 2 0 2 1 1]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [60]:
Z = np.random.random([10,10]) + 0.5
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5314367858515917


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [72]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print(it.operands[2])
print(A + B) # it is the same as A + B

[[0 1 2]
 [1 2 3]
 [2 3 4]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [80]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [90]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
# Z += np.bincount(I, minlength=len(Z))
# print(I)
# print(Z)
np.add.at(Z, I, 1)
print(Z)

[5. 2. 2. 4. 2. 2. 2. 4. 3. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [110]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
# weights=X
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [119]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [134]:
A = np.ones((5, 5, 5, 5))
print(np.sum(A, (-2, -1)))

[[25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]
 [25. 25. 25. 25. 25.]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [32]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,20,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.4866342  0.51572343 0.65705544 0.50676666 0.51420537 0.31067758
 0.56822497 0.57058312 0.2537517  0.46464477 0.70791682 0.45014669
 0.65004718 0.47063191 0.40477677 0.63036544 0.3968605  0.59711099
 0.63346158 0.51945705]
0     0.486634
1     0.515723
2     0.657055
3     0.506767
4     0.514205
5     0.310678
6     0.568225
7     0.570583
8     0.253752
9     0.464645
10    0.707917
11    0.450147
12    0.650047
13    0.470632
14    0.404777
15    0.630365
16    0.396860
17    0.597111
18    0.633462
19    0.519457
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [40]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

print(np.dot(A, B))

print(np.sum(A * B.T, axis=1))


[[1.15899781 2.19905125 1.41582793 1.41934732 1.45933613]
 [1.47777144 2.61794916 1.48320937 1.93651746 1.20776642]
 [0.73264349 1.39193191 0.64895576 0.97591305 0.72446249]
 [1.09037113 2.17679545 1.28606372 1.68648819 0.8010472 ]
 [1.07459742 2.06533235 1.47278624 1.62082002 0.85341151]]
[1.15899781 2.61794916 0.64895576 1.68648819 0.85341151]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [41]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)